export const POINT_IMG_OPTIONS = [
  { className: "icon-restaurant", label: "餐饮", position: [-56, -28] },
  { className: "icon-accommodation", label: "住宿", position: [-1, -1] },
  { className: "icon-shopping", label: "购物", position: [-222, -1] },
  { className: "icon-automobile", label: "4s店", position: [-194, -28] },
  { className: "icon-finance", label: "金融", position: [-166, -1] },
  { className: "icon-culture", label: "教育", position: [-111, -1] },
  { className: "icon-hygiene", label: "卫生", position: [-29, -1] },
  { className: "icon-sports", label: "休闲", position: [-56, -1] },
  { className: "icon-office", label: "机关", position: [-194, -1] },
  { className: "icon-storage", label: "商业", position: [-84, -28] },
  { className: "icon-life", label: "服务", position: [-84, -1] },
  { className: "icon-company", label: "公司", position: [-1, -28] },
  { className: "icon-traffic", label: "交通", position: [-139, -1] },
  {
    className: "icon-scientific-research",
    label: "科研",
    position: [-29, -28],
  },
  { className: "icon-agriculture", label: "农业", position: [-111, -28] },
  { className: "icon-place-name", label: "地名", position: [-166, -28] },
  { className: "icon-facilities", label: "设施", position: [-139, -28] },
];